# Generated by Django 3.0.2 on 2020-01-20 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Тесто')),
            ],
            options={
                'verbose_name': 'Тесто',
                'verbose_name_plural': 'Виды теста',
            },
        ),
        migrations.CreateModel(
            name='ToppingGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Группа начинок')),
            ],
            options={
                'verbose_name': 'Группа начинок',
                'verbose_name_plural': 'Группы начинок',
            },
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Начинка')),
                ('price', models.FloatField(max_length=3)),
                ('topping_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toppings', to='pizza.ToppingGroup')),
            ],
            options={
                'verbose_name': 'Начинка',
                'verbose_name_plural': 'Начинки',
            },
        ),
    ]
