# Generated by Django 3.0.2 on 2020-01-26 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topping',
            options={'ordering': ['name'], 'verbose_name': 'Начинка', 'verbose_name_plural': 'Начинки'},
        ),
        migrations.AlterField(
            model_name='topping',
            name='price',
            field=models.FloatField(max_length=5),
        ),
        migrations.CreateModel(
            name='ToppingAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('topping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pizza.Topping')),
            ],
        ),
    ]
